# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucketlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('bucketlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bucketlist')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('bucketlist', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='bucketlist',
            unique_together=set([('created_by', 'name')]),
        ),
    ]
